### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by dokbua** [linuxserver/docker-headphones#46]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

root@gw:~/docker/headphones# wget localhost:8181
--2019-09-24 23:09:27--  http://localhost:8181/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8181... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-09-24 23:09:28--  (try: 2)  http://localhost:8181/
Connecting to localhost (localhost)|::1|:8181... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-09-24 23:09:30--  (try: 3)  http://localhost:8181/
Connecting to localhost (localhost)|::1|:8181... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

Trying same in a browser cause it to flash and err with the error mentioned in the subject field.

	

Linux (Debian)

```
# cat docker-compose.yml
version: "2"
services:
  headphones:
    image: linuxserver/headphones
    container_name: headphones
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./music:/music
    ports:
      - 8181:8181
    restart: unless-stopped
```

```
root@gw:~/docker/headphones# docker logs headphones
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
24-Sep-2019 22:07:56 - INFO :: MainThread : Checking to see if the database has all tables....
24-Sep-2019 22:07:56 - INFO :: MainThread : Retrieving latest version information from GitHub
24-Sep-2019 22:07:57 - INFO :: MainThread : Headphones is up to date
24-Sep-2019 22:07:57 - INFO :: MainThread : Starting Headphones web server on http://localhost:8181/
24-Sep-2019 22:07:57 - INFO :: MainThread : Scheduled background task: Search for Wanted
24-Sep-2019 22:07:57 - INFO :: MainThread : Scheduled background task: Download Scan
24-Sep-2019 22:07:57 - INFO :: MainThread : Scheduled background task: Library Scan
24-Sep-2019 22:07:57 - INFO :: MainThread : Scheduled background task: MusicBrainz Update
24-Sep-2019 22:07:57 - INFO :: MainThread : Scheduled background task: Check GitHub for updates
```

I'm not
