### ISSUE TITLE
mac decoder not installed

### ISSUE THREAD

**Issue by Vesyrak** [linuxserver/docker-headphones#49]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
When using the headphones docker image to post-process .ape files, these get split and processed correctly

## Current Behavior
The shntool doesn't find the mac codec, and fails to split the file

## Steps to Reproduce
1. Get a .cue and .ape file that headphones should split
2. Using the webinterface, go to Settings -> Quality & Post Processing -> Check "Split single file albums into multiple tracks"
3. Using the webinterface, go to Manage -> Force Actions -> Force Post-Process Albums in Alternate Folder -> Point to dir where .cue and .ape files are and request post-processing
4. View Logs showing split failed

## Environment
**OS:** Ubuntu 18.04      
**CPU architecture:** x86_64     
**How docker service was installed:**  docker-compose

## Command used to create docker container (run/create/compose/screenshot)
```
version: "3"
services:
  headphones:
    image: linuxserver/headphones
    container_name: headphones
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /drive/DockerConfigs/Headphones/Config:/config
      - /drive/Torrents:/downloads
      - /drive/Music:/music
```

## Docker logs
Docker spits out too much logs, below the error:
```
root@1a0383901b06:/downloads/Headphones/MusicDownloads/Duran Duran (Unprocessed)/1993 - The Wedding Album (2xCD)/CD2# /usr/bin/shntool split -f Duran\ Duran\ -\ The\ Wedding\ Album\ \(CD\ 2\).cue -o ape Duran\ Duran\ -\ The\ Wedding\ Album\ \(CD\ 2\).ape 
shntool [split]: warning: failed to read data from input file using format: [ape]
shntool [split]:          + you may not have permission to read file: [Duran Duran - The Wedding Album (CD 2).ape]
shntool [split]:          + arguments may be incorrect for decoder: [mac]
shntool [split]:          + verify that the decoder is installed and in your PATH
shntool [split]:          + this file may be unsupported, truncated or corrupt
shntool [split]: error: cannot continue due to error(s) shown above
```
